### ISSUE TITLE
Can't reload

### ISSUE THREAD

**Issue by Khybersghost** [kristkos/kctg-common#5] opened 2023-07-05 07:03 UTC
Foundry V10-291
PF2e System
Ran into a strange issue that I am pretty sure this module is responsible for. 
Basically, when I first start my server and load in, everything works fine. If I have to refresh for any reason, it won't load back in. The server is basically crippled at that point. Logging out and trying to log back in won't work. Players can't log in. The only thing that works is stopping the server completely and restarting. Find the Culprit helped me isolate the issue to this mod (as far as I can tell) and removing it has fixed my issue.

**Comment by kristkos** [comment] 2023-07-05 07:27
Hello there,
Please provide the following information:
Hosting method, as well as, what error you receive when you open the server from the console(F12).
I've attempted to recreate locally but was unable to recreate the issue. One las mention, what version of the module you're currently using?
As I've done a small update to v11 on some files can you try v0.12 via installing manually?

**Comment by Khybersghost** [comment] 2023-07-05 16:14
Currently using The Forge as a hosting service. The console didn't generate any errors oddly it just choked after the first few lines of code. 

Host: Forge
Mod Ver: 0.13
Foundry Ver: 10-291
PF2e Ver: 4.12.9

**Comment by thelouisrex** [comment] 2023-07-06 17:16
5e - v2.2.1
Foundry - v10.291
Mod ver - v0.13
No hosting service just on the pc programme

I'm having this same issue, just updated a feew modules, had this issue where everything worked fine but reloading would essentially stop the programme (not 'not responding' or anything like that as best I can tell), just stuck on foundry's version of a loading screen.

Disabled every module apart from this one still gives me the issue, enabled every module apart from this one doesn't have the issue.

**Comment by kszczepanskidev** [comment] 2023-07-06 20:53
5e - v2.2.1
Foundry - v10.303
Mod ver - v0.13

Also have the issue, the foundry canvas and content loads only once and then it's stuck on the empty screen. Same behaviour for player or GM, cannot load the game for 2 players even as it bricks.
Downloaded the 0.12a module from github and it works okay.

**Comment by azarius74** [comment] 2023-07-07 19:39
Can confirm this is happening in our Forge world, exactly the same issue.  Kakaroto and Phi from the Forge helped us narrow it down.

"it's a long standing bug in Foundry that if it fails to load a compendium pack's data, it will stop responding to users logging in and will never serve them the world's data, causing the issue you've been having.  based on the error message "illegal operation on a directory", this tells me that the module released with v11 specific packs (which are a directory) but you're on foundry v10 (which expects a file)

5e: v.10.303
Mod Ver - v0.13

DM deactivated mod and world loads as normal.

**Comment by kristkos** [comment] 2023-08-01 11:22
Hello folks,

Apologies for the delay, version 0.12 should work as intended for Forge alone, please be advised this is not a Foundry bug, it's a Forge bug. The issue lies here with Forge and since I do not have a live version of it, I cannot trouble shoot and it creates some issues. I've placed in the Foundry admin restrictions for versioning, but somehow my pack of 0.13 on forge, still sip trough. This should be sorted with v11. 

The issue lies in the manifest file, where it tries to read both versions to provide updates, but it cannot differentiate between version 11 and 10 of foundry. However on the foundry admin/client(not on Forge hosted) page it does separate based on the overall client version, which forge does not do, as they have a different update system.

**Closed as completed** 2023-11-20 22:35 UTC
